<a href="https://colab.research.google.com/github/Vishwa2488/main/blob/main/pytorch_machine_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)



2.0.1+cu118


Tensors

In [ ]:
#scalar
scalar=torch.tensor(5)

d1=torch.tensor([3,5,4])
print(d1)

print(scalar)


tensor([3, 5, 4])
tensor(5)


In [ ]:
#ndim=find dimension of tensor
print(scalar.ndim)
print(d1.ndim)



0
1


In [ ]:
#to get tensor to python integer
print(scalar.item())
#d1.item() gives error. only for scalar




5


In [ ]:
#vector
d1=torch.tensor([1,2,3])

print(d1.ndim)

print("shape of vector=",d1.shape)


1
shape of vector= torch.Size([3])


In [ ]:
#matrix

matrix=torch.tensor([[1,2],[3,4]])

matrix

tensor([[1, 2],
        [3, 4]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix.shape




torch.Size([2, 2])

In [ ]:
matrix[1]

tensor([3, 4])

In [ ]:
matrix[1][0]


tensor(3)

In [ ]:
matrix[0,0]


tensor(1)

In [ ]:
#TENSOR
TENSOR=torch.tensor([[[1,2],[4,5],[7,8]]])
TENSOR

tensor([[[1, 2],
         [4, 5],
         [7, 8]]])

In [ ]:
TENSOR.ndim


3

In [ ]:
TENSOR.shape


torch.Size([1, 3, 2])

In [ ]:
TENSOR.type

<function Tensor.type>

In [ ]:
#form numpy array
array=np.array([[1,2,3],[3,4,5]])
tensor=torch.from_numpy(array)
tensor


tensor([[1, 2, 3],
        [3, 4, 5]])

why random tensors?
random tensors are importants because the neural networks start from random numbers. So this is required.


Neural Network
start with random numbers-look at data-correct it..


In [ ]:
#creating random tensor
random_tensor=torch.rand(3,4)
random_tensor






tensor([[0.8248, 0.5896, 0.4371, 0.5365],
        [0.4165, 0.8400, 0.9502, 0.4178],
        [0.8589, 0.2154, 0.6879, 0.6427]])

In [ ]:
rand_tensor=torch.rand(10,10)
rand_tensor


tensor([[0.2999, 0.4872, 0.4319, 0.3696, 0.2361, 0.8303, 0.8776, 0.7299, 0.0019,
         0.5282],
        [0.0837, 0.1295, 0.1134, 0.8281, 0.7401, 0.8522, 0.5229, 0.6568, 0.8130,
         0.5683],
        [0.2289, 0.1712, 0.3612, 0.1464, 0.7911, 0.0024, 0.6774, 0.0895, 0.2222,
         0.8120],
        [0.7477, 0.0485, 0.8582, 0.5952, 0.8471, 0.9978, 0.2488, 0.9063, 0.1661,
         0.0496],
        [0.9705, 0.1274, 0.6213, 0.5124, 0.6091, 0.5419, 0.6399, 0.2869, 0.2058,
         0.4069],
        [0.9463, 0.7391, 0.7524, 0.4590, 0.4028, 0.5297, 0.6298, 0.5869, 0.7302,
         0.7241],
        [0.0765, 0.4267, 0.1232, 0.9451, 0.6692, 0.8911, 0.5560, 0.3683, 0.1493,
         0.4585],
        [0.6556, 0.2226, 0.4903, 0.8939, 0.0792, 0.0191, 0.4760, 0.9848, 0.7462,
         0.4211],
        [0.7231, 0.8501, 0.8282, 0.9105, 0.7470, 0.5307, 0.5217, 0.4709, 0.5357,
         0.3076],
        [0.5821, 0.0172, 0.3752, 0.7227, 0.9209, 0.7723, 0.4666, 0.4445, 0.0434,
         0.6765]])

In [ ]:
rand_tensor.ndim


2

In [ ]:
# create random tensor with similar shape as an image
random_image_size_tensor=torch.rand(size=(224,224,3)) #can also be (3,224,224)
random_image_size_tensor.shape


torch.Size([224, 224, 3])

In [ ]:
randtensor=torch.rand(3,1,5)
randtensor

tensor([[[0.4826, 0.2833, 0.6096, 0.5209, 0.7859]],

        [[0.7711, 0.8450, 0.8194, 0.0928, 0.4919]],

        [[0.5026, 0.3641, 0.5963, 0.4284, 0.3104]]])

In [ ]:
#create tensor of 0
zero=torch.zeros(3,4) # or torch.zero(size=(3,4))
zero


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones=torch.ones(3,4)


In [ ]:
ones.dtype,ones.type #datatype is float by default



(torch.float32, <function Tensor.type>)

creating a range of tensors and tensors-like

In [ ]:
#torch.range is old. SO use torch.arange
tensor=torch.arange(0,100,4)
tensor


tensor([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64, 68,
        72, 76, 80, 84, 88, 92, 96])

In [ ]:
#tensors like
zeros_like=torch.zeros_like(tensor)
zeros_like


tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0])

tensor datatypes

Note: There can be three errors mainly in pytorch that you can get.
1. Tensor not right datatype
2. tensor not right shape
3. tensor not on the right device


In [ ]:
#tensor datatype

float_32_tensor= torch.tensor([3.0,6.0,9.0],
                              dtype=None,  #data type 
                              device=None, #can be None, "cpu", cuda,..
                              requires_grad=False)# whether or not to track gradients with this tensor
float_32_tensor



tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype



torch.float32

In [ ]:
float_16_tensor= float_32_tensor.type(torch.float16)
float_16_tensor



tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor+float_32_tensor

tensor([ 6., 12., 18.])

In [ ]:
float_16_tensor*float_32_tensor


tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor=torch.tensor([3,6,9],dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
float_32_tensor*int_32_tensor


tensor([ 9., 36., 81.])

Tensor Attributes

In [ ]:
# creating tensor
T=torch.rand(size=(5,2))




In [ ]:
# find out details about some tensor
print(T)

print(f"Datatype of tensor: {T.dtype}")
print(f"size or shape of tensor: {T.shape}") # can also use T.size()
print(f"device of tensor: {T.device}")
print(f"type of tensor: {T.type}") 


tensor([[0.5767, 0.5070],
        [0.5892, 0.3198],
        [0.6137, 0.0434],
        [0.8591, 0.3192],
        [0.6183, 0.3259]])
Datatype of tensor: torch.float32
size or shape of tensor: torch.Size([5, 2])
device of tensor: cpu
type of tensor: <built-in method type of Tensor object at 0x7fa9c912a840>


Manipulating Tensors (tensor operations)
tensor operations


*  Addition
*  Subtraction
*  Multiplication(element wise)
*  Division 
*  Matrix multiplication


In [ ]:
# create tensor
tensor=torch.tensor([1,2,3])
tensor+10


tensor([11, 12, 13])

In [ ]:
#multiplying tensor
tensor*4


tensor([ 4,  8, 12])

In [ ]:
#divide
tensor/10


tensor([0.1000, 0.2000, 0.3000])

In [ ]:
#subtraction
tensor=tensor-10
tensor

tensor+10



tensor([1, 2, 3])

In [ ]:
#tensor operation with functions (not recommended generally)

print(torch.mul(tensor,10))
print(torch.add(tensor,10))



tensor([-90, -80, -70])
tensor([1, 2, 3])


In [ ]:
#element wise multiplication
print(tensor*tensor)


tensor([81, 64, 49])


In [ ]:
%%time
#matrix multiplication-use this function for fast calculation
# it is optimised. time is generally of ms order for python. 
# so it is very fast.
torch.matmul(tensor,tensor)


CPU times: user 1.63 ms, sys: 102 µs, total: 1.73 ms
Wall time: 1.96 ms


tensor(194)

In [ ]:
%%time

tensor@tensor # @ is operator for matrix mult
# slower and not understandable easily

CPU times: user 44 µs, sys: 8 µs, total: 52 µs
Wall time: 55.3 µs


tensor(194)

One of the most common deep learning errors are shape errors.

#The inner dimensions must match
#The result has the shape of outer dimensions
 @ is symbol for matrix multiplication.
 Dont use it as it is slower and not as clear as matmul


In [ ]:
# this will give error as inner dimensions dont match
# try it
#torch.matmul(torch.rand(2,3),torch.rand(2,3))


In [ ]:
tensor1=torch.rand(2,3)
tensor2=torch.rand(3,2)
print("tensor1=",tensor1)
print("tensor2=",tensor2)

torch.matmul(tensor1,tensor2)



tensor1= tensor([[0.5288, 0.2456, 0.9860],
        [0.0345, 0.2745, 0.6572]])
tensor2= tensor([[0.5377, 0.8943],
        [0.4376, 0.1805],
        [0.6356, 0.4037]])


tensor([[1.0185, 0.9153],
        [0.5563, 0.3457]])

In [ ]:
tensor1 = torch.rand(2,3)
tensor2=torch.rand(2,3)

#torch.mm(tensor1,tensor2) gives a short for torch.matmul()

#torch.mm(tensor1,tensor2) gives error due to shape error

torch.mm(tensor1,tensor2.T),torch.mm(tensor1,tensor2.T).shape
 # transposing tensor2


(tensor([[0.3133, 0.9283],
         [0.2240, 0.6800]]),
 torch.Size([2, 2]))

Finding the min,max,mean,sum,etc (called tensor aggregation)

In [ ]:
x=torch.arange(0,100,4)
tensor


tensor([-9, -8, -7])

In [ ]:
#find min and max
torch.min(x),torch.max(x)


(tensor(0), tensor(96))

In [ ]:
#find mean-torch.mean() requires a tensor of float32 datatype to work

torch.mean(x.type(torch.float32))



tensor(48.)

In [ ]:
#find the sum

torch.sum(x)


tensor(1200)

In [ ]:
# find posiion of element of tensor with minimium value

x.argmin(),x[0]

(tensor(0), tensor(0))

In [ ]:
#finding the position in tensor that has the maximum value with argmax()

x.argmax(),x[24]


(tensor(24), tensor(96))

#reshaping ,stacking, squeezing and unsqueezing

*reshaping-reshapes an input tensor to a defined shape
*View -Return a view of an input tensor of certain shape but keeps the memory intact
stacking-combine multiple tensors on top of each other (vstack-vertical stack) or side by side (hstack-horizontal stack)
* squeeze -removes all '1' dimensions from a  tensor
*unsqueeze-add a 1 dimension to a target tensor
*permute -return a view of the input with dimensions permuted (give a permutation) in a certain way





In [ ]:
x=torch.arange(1.,10.)
x,x.shape





(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# adding an extra dimension
x_reshaped=x.reshape(9,1) #9*1=1*9
x_reshaped,x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [ ]:
x_reshaped=x.reshape(3,3)  #3*3=1*9
x_reshaped,x_reshaped.shape


(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [ ]:
x_reshaped=x.reshape(3,4)  #3*4>1*9

x_reshaped,x_reshaped.shape

RuntimeError: ignored

In [ ]:
x_reshaped=x.reshape(3,2) #3*2<1*9
x_reshaped,x_reshaped.shape


RuntimeError: ignored

In [ ]:
#change the view
z=x.view(1,9)
z,z.shape



(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
#changing z changes x also as z points to the same memory as x
z[0,3:]=2
z,x


(tensor([[1., 2., 3., 2., 2., 2., 2., 2., 2.]]),
 tensor([1., 2., 3., 2., 2., 2., 2., 2., 2.]))

In [ ]:
#stacking tensors on the top of each other
x_stacked=torch.stack([x,x,x,x,x],dim=0)
x_stacked

tensor([[1., 2., 3., 2., 2., 2., 2., 2., 2.],
        [1., 2., 3., 2., 2., 2., 2., 2., 2.],
        [1., 2., 3., 2., 2., 2., 2., 2., 2.],
        [1., 2., 3., 2., 2., 2., 2., 2., 2.],
        [1., 2., 3., 2., 2., 2., 2., 2., 2.]])

In [ ]:
a=torch.tensor([1,2,3])
b=torch.tensor([4,5,6])
torch.hstack((a,b)),torch.vstack((a,b))



(tensor([1, 2, 3, 4, 5, 6]),
 tensor([[1, 2, 3],
         [4, 5, 6]]))

In [ ]:
a=torch.tensor([[1],[2],[3]])
b=torch.tensor([[4],[5],[6]])
torch.hstack((a,b)),torch.vstack((a,b))




(tensor([[1, 4],
         [2, 5],
         [3, 6]]),
 tensor([[1],
         [2],
         [3],
         [4],
         [5],
         [6]]))

In [ ]:
#torch.squeeze()-removes all single dimensions from the target tensor
x=x.reshape((1,1,9))
print(x,x.shape)

x=x.squeeze()

print(x,x.shape)




tensor([[[1., 2., 3., 2., 2., 2., 2., 2., 2.]]]) torch.Size([1, 1, 9])
tensor([1., 2., 3., 2., 2., 2., 2., 2., 2.]) torch.Size([9])


In [ ]:
x=x.reshape((3,1,3))
print(x,x.shape)

x=x.squeeze()

print(x,x.shape)




tensor([[[1., 2., 3.]],

        [[2., 2., 2.]],

        [[2., 2., 2.]]]) torch.Size([3, 1, 3])
tensor([[1., 2., 3.],
        [2., 2., 2.],
        [2., 2., 2.]]) torch.Size([3, 3])


In [ ]:

#torch.unsqueeze()-adds a single dimension to a target at a specific dim (dimension)
print(f"previous target: {x}")
print(f"previous shape: {x.shape}")

#below, dim must not be more than 2 as there are 2 dimensions already.
# and we can add only one dimension when we unqueeze

print(f"\nafter unsqueezing: {x.unsqueeze(dim=1)}") 
print(f"after unsqueezing shape:{x.unsqueeze(dim=1).shape}")


previous target: tensor([[1., 2., 3.],
        [2., 2., 2.],
        [2., 2., 2.]])
previous shape: torch.Size([3, 3])

after unsqueezing: tensor([[[1., 2., 3.]],

        [[2., 2., 2.]],

        [[2., 2., 2.]]])
after unsqueezing shape:torch.Size([3, 1, 3])


In [ ]:
#torch.permute-rearrange the dimensions of a target tenosr in a specified order
x_original=torch.rand(size=(224,224,3)) 
#permuting the 